#!/usr/bin/env python2.7
import os, sys
path = ['/usr/local/lib/python2.7/site-packages']
for p in os.environ.get("WMII_CONFPATH", "").split(':'):
    path += [p, p + '/python']
print(path)
sys.path = path + sys.path

import wmiirc_before

from pygmi import events
import wmiirc

events.loop()

